language: erlang
otp_release:
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
script:
 - rebar -C rebar.proper.config clean get-deps compile && rebar -C rebar.proper.config eunit skip_deps=true
